package PVE::API2::UPS::Config;

# PVE::API2::UPS::Config
# 掛載於 /nodes/{node}/ups/config
# 提供裝置 CRUD、全域模式設定、服務重啟端點。

use strict;
use warnings;

use PVE::RESTHandler;
use PVE::JSONSchema qw(get_standard_option);
use PVE::RPCEnvironment;
use PVE::Tools qw(run_command);

use base qw(PVE::RESTHandler);

my $NUT_CONF    = '/etc/nut/nut.conf';
my $UPS_CONF    = '/etc/nut/ups.conf';
my $UPSMON_CONF = '/etc/nut/upsmon.conf';
my $UPSD_CONF   = '/etc/nut/upsd.conf';
my $UPSD_USERS  = '/etc/nut/upsd.users';

# pve-ups-notify 透過 sudo 以 root 執行（sudoers.d 已在安裝時設定）
my $NOTIFY_CMD  = '/usr/bin/sudo -n /usr/lib/pve-ups-panel/pve-ups-notify';

# ── 輔助函式 ────────────────────────────────────────────────────────────────

sub _generate_upsd_conf {
    my ($listen_addr) = @_;
    $listen_addr //= '127.0.0.1';
    return "# Generated by pve-ups-panel\nLISTEN $listen_addr 3493\nMAXCONN 1024\n";
}

sub _read_upsd_conf {
    my %conf = (listen_addr => '127.0.0.1');
    return %conf unless -f $UPSD_CONF;
    open(my $fh, '<', $UPSD_CONF) or return %conf;
    while (<$fh>) {
        $conf{listen_addr} = $1 if /^LISTEN\s+(\S+)/;
    }
    close $fh;
    return %conf;
}

# 解析 upsd.users → { username => { password, upsmon, instcmds, actions } }
sub _parse_upsd_users {
    my %users;
    return %users unless -f $UPSD_USERS;
    open(my $fh, '<', $UPSD_USERS) or return %users;
    my $cur;
    while (<$fh>) {
        chomp; s/#.*//; s/^\s+|\s+$//g; next unless $_;
        if (/^\[([^\]]+)\]/) {
            $cur = $1; $users{$cur} = {};
        } elsif ($cur) {
            $users{$cur}{password} = $1 if /^password\s*=\s*(.+)$/;
            $users{$cur}{upsmon}   = $1 if /^upsmon\s+(\S+)/;
            $users{$cur}{instcmds} = $1 if /^instcmds\s*=\s*(.+)$/i;
            $users{$cur}{actions}  = $1 if /^actions\s*=\s*(.+)$/i;
        }
    }
    close $fh;
    return %users;
}

# 讀取現有 upsmon_local 密碼，否則產生新的 32 字元隨機密碼
sub _get_or_create_local_password {
    my %users = _parse_upsd_users();
    return $users{upsmon_local}{password}
        if $users{upsmon_local} && $users{upsmon_local}{password};
    my @chars = ('a'..'z', 'A'..'Z', '0'..'9');
    return join('', map { $chars[int(rand(scalar @chars))] } 1..32);
}

sub _write_file_safe {
    my ($file, $content) = @_;
    my $tmp = "$file.tmp.$$";
    open(my $fh, '>', $tmp) or die "Cannot write $tmp: $!\n";
    print $fh $content;
    close $fh;
    rename($tmp, $file) or die "Cannot replace $file: $!\n";
}

sub _read_nut_mode {
    return 'standalone' unless -f $NUT_CONF;
    open(my $fh, '<', $NUT_CONF) or return 'standalone';
    while (<$fh>) {
        return $1 if /^\s*MODE\s*=\s*(\S+)/i;
    }
    close $fh;
    return 'standalone';
}

sub _generate_nut_conf {
    my ($mode) = @_;
    return "# Generated by pve-ups-panel\nMODE=$mode\n";
}

# 從 driver 名稱判斷裝置類型
sub _device_type {
    my ($driver) = @_;
    return 'snmp' if ($driver // '') eq 'snmp-ups';
    return 'usb';
}

# 解析 ups.conf → [{name, driver, port, ...}]
sub _parse_ups_conf {
    my @devices;
    return @devices unless -f $UPS_CONF;
    my $cur;
    open(my $fh, '<', $UPS_CONF) or return @devices;
    while (<$fh>) {
        chomp;
        s/\s*#.*$//;
        if (/^\[([^\]]+)\]/) {
            push @devices, $cur if $cur;
            $cur = { name => $1 };
        } elsif ($cur && /^\s*(\w+)\s*=\s*"?([^"]*)"?\s*$/) {
            $cur->{lc $1} = $2;
        }
    }
    push @devices, $cur if $cur;
    close $fh;
    return @devices;
}

sub _generate_ups_conf {
    my (@devices) = @_;
    my $out = "# Generated by pve-ups-panel\n\n";
    for my $d (@devices) {
        $out .= "[$d->{name}]\n";
        $out .= "    driver = $d->{driver}\n"              if $d->{driver};
        $out .= "    port = $d->{port}\n"                  if $d->{port};
        # USB 專用欄位
        $out .= "    serial = $d->{serial}\n"              if $d->{serial};
        $out .= "    vendorid = $d->{vendorid}\n"          if $d->{vendorid};
        $out .= "    productid = $d->{productid}\n"        if $d->{productid};
        # SNMP 專用欄位
        $out .= "    community = $d->{community}\n"        if $d->{community};
        $out .= "    snmp_version = $d->{snmp_version}\n"  if $d->{snmp_version};
        $out .= "    mibs = $d->{mibs}\n"                  if $d->{mibs};
        # SNMPv3 欄位（_parse_ups_conf 以 lc 儲存 key，此處對應寫回 NUT 原始大小寫）
        $out .= "    secLevel     = $d->{seclevel}\n"     if $d->{seclevel};
        $out .= "    secName      = $d->{secname}\n"      if $d->{secname};
        $out .= "    authProtocol = $d->{authprotocol}\n" if $d->{authprotocol};
        $out .= "    authPassword = $d->{authpassword}\n" if $d->{authpassword};
        $out .= "    privProtocol = $d->{privprotocol}\n" if $d->{privprotocol};
        $out .= "    privPassword = $d->{privpassword}\n" if $d->{privpassword};
        $out .= "    desc = \"$d->{desc}\"\n"              if $d->{desc};
        $out .= "\n";
    }
    return $out;
}

# 解析 upsmon.conf MONITOR 行 → [{name, host, port, username, password, montype}]
sub _parse_monitor_lines {
    my @monitors;
    return @monitors unless -f $UPSMON_CONF;
    open(my $fh, '<', $UPSMON_CONF) or return @monitors;
    while (<$fh>) {
        if (/^MONITOR\s+(\S+)\s+\d+\s+(\S+)\s+(\S+)\s+(\S+)/) {
            my ($target, $user, $pass, $montype) = ($1, $2, $3, $4);
            if ($target =~ /^([^@]+)\@([^:]+)(?::(\d+))?$/) {
                push @monitors, {
                    name     => $1,
                    host     => $2,
                    port     => defined $3 ? $3 + 0 : 3493,
                    username => $user,
                    password => $pass,
                    montype  => $montype,
                };
            }
        }
    }
    close $fh;
    return @monitors;
}

# 從 monitor 清單產生完整 upsmon.conf。
# NOTIFYCMD 固定寫入（裝置設定後 hook 即可用）；
# NOTIFYFLAG 從現有檔案保留（由 Notify.pm 在儲存通知規則時管理）。
sub _build_upsmon_conf {
    my ($monitors) = @_;

    # 只保留 NOTIFYFLAG 行（NOTIFYCMD 改為固定寫入，不依賴現有檔案）
    my @flag_lines;
    if (-f $UPSMON_CONF) {
        open(my $fh, '<', $UPSMON_CONF) or goto SKIP_FLAGS;
        while (<$fh>) {
            push @flag_lines, $_ if /^NOTIFYFLAG\s/;
        }
        close $fh;
    }
    SKIP_FLAGS:

    my $out = "# Generated by pve-ups-panel\n\n";
    for my $m (@$monitors) {
        my $target = "$m->{name}\@$m->{host}";
        $target .= ":$m->{port}" if $m->{host} ne 'localhost' && $m->{port} != 3493;
        $out .= "MONITOR $target 1 $m->{username} $m->{password} $m->{montype}\n";
    }
    $out .= <<'END';

SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
POWERDOWNFLAG /etc/killpower
RBWARNTIME 43200
NOCOMMWARNTIME 300
FINALDELAY 5
END
    # 固定寫入 NOTIFYCMD，確保 hook 在裝置設定後即可運作
    $out .= "\nNOTIFYCMD $NOTIFY_CMD\n";
    $out .= join('', @flag_lines) if @flag_lines;
    return $out;
}

sub _generate_upsd_users {
    my ($local_pass, $remote_user, $remote_pass) = @_;
    my $out = "# Generated by pve-ups-panel\n";
    # 本機監控帳號：master + 完整指令與設定權限（電池測試等需要）
    $out .= "[upsmon_local]\n";
    $out .= "    password = $local_pass\n";
    $out .= "    upsmon master\n";
    $out .= "    instcmds = ALL\n";
    $out .= "    actions = SET\n";
    # 可選遠端監控帳號（slave，唯讀）
    if (defined $remote_user && $remote_user ne '' &&
        defined $remote_pass && $remote_pass ne '') {
        $out .= "\n[$remote_user]\n";
        $out .= "    password = $remote_pass\n";
        $out .= "    upsmon slave\n";
    }
    return $out;
}

sub _check_device_status {
    my ($target) = @_;
    my $connected = 0;
    eval {
        open(my $fh, '-|', '/bin/upsc', $target) or die;
        while (<$fh>) { if (/^ups\.status:/) { $connected = 1; last; } }
        close $fh;
    };
    return $connected ? 'connected' : 'disconnected';
}

sub _ensure_nut_dir {
    unless (-d '/etc/nut') {
        mkdir '/etc/nut', 0750 or die "Cannot create /etc/nut: $!\n";
    }
}

sub _fix_nut_perms {
    run_command(['chown', '-R', 'root:nut', '/etc/nut'],
        errmsg => 'chown /etc/nut failed', noerr => 1);
    for my $f ($NUT_CONF, $UPS_CONF, $UPSMON_CONF, $UPSD_CONF, $UPSD_USERS) {
        chmod 0640, $f if -f $f;
    }
}

sub _restart_services {
    my ($mode) = @_;
    if (($mode // '') eq 'standalone' || ($mode // '') eq 'netserver') {
        eval { run_command(['systemctl', 'restart', 'nut-server'], errmsg => 'restart nut-server') };
        warn "nut-server restart: $@" if $@;
        sleep 1;
    }
    eval { run_command(['systemctl', 'restart', 'nut-monitor'], errmsg => 'restart nut-monitor') };
    warn "nut-monitor restart: $@" if $@;
}

# ── GET /ups/config/mode ───────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'get_mode',
    path        => 'mode',
    method      => 'GET',
    description => '取得目前 NUT 全域模式（standalone / netserver）。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Audit']] },
    parameters  => {
        additionalProperties => 0,
        properties => { node => get_standard_option('pve-node') },
    },
    returns => {
        type => 'object',
        properties => { mode => { type => 'string' } },
        additionalProperties => 0,
    },
    code => sub { return { mode => _read_nut_mode() }; },
});

# ── PUT /ups/config/mode ───────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'set_mode',
    path        => 'mode',
    method      => 'PUT',
    description => '設定 NUT 全域模式（standalone / netserver）並重啟相關服務。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            mode => { type => 'string', enum => ['standalone', 'netserver'] },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        _ensure_nut_dir();
        _write_file_safe($NUT_CONF, _generate_nut_conf($param->{mode}));
        # 依模式調整 upsd 監聽位址：
        #   standalone → 只監聽 localhost；
        #   netserver  → 若目前是 localhost 則開放全網路，否則保留現有設定
        my %upsd = _read_upsd_conf();
        my $listen = $upsd{listen_addr};
        if ($param->{mode} eq 'standalone') {
            $listen = '127.0.0.1';
        } elsif ($listen eq '127.0.0.1') {
            $listen = '0.0.0.0';
        }
        _write_file_safe($UPSD_CONF, _generate_upsd_conf($listen));
        _fix_nut_perms();
        _restart_services($param->{mode});
        return undef;
    },
});

# ── GET /ups/config/devices ────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'list_devices',
    path        => 'devices',
    method      => 'GET',
    description => '列出所有 UPS 裝置（本機 USB/SNMP + 遠端 NUT Server MONITOR）。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Audit']] },
    parameters  => {
        additionalProperties => 0,
        properties => { node => get_standard_option('pve-node') },
    },
    returns => {
        type  => 'array',
        items => {
            type => 'object',
            properties => {
                name         => { type => 'string' },
                type         => { type => 'string', description => 'usb | snmp | remote' },
                status       => { type => 'string', description => 'connected | disconnected' },
                driver       => { type => 'string', optional => 1 },
                port         => { type => 'string', optional => 1 },
                host         => { type => 'string', optional => 1 },
                nutport      => { type => 'integer', optional => 1 },
                snmp_version => { type => 'string',  optional => 1 },
                community    => { type => 'string',  optional => 1 },
                mibs         => { type => 'string',  optional => 1 },
                seclevel     => { type => 'string',  optional => 1 },
                secname      => { type => 'string',  optional => 1 },
                authprotocol => { type => 'string',  optional => 1 },
                privprotocol => { type => 'string',  optional => 1 },
            },
            additionalProperties => 1,
        },
    },
    code => sub {
        my @result;
        my %local_names;

        # 本機裝置（ups.conf）
        for my $d (_parse_ups_conf()) {
            my $type = _device_type($d->{driver});
            $local_names{$d->{name}} = 1;
            push @result, {
                %$d,
                type   => $type,
                status => _check_device_status("$d->{name}\@localhost"),
            };
        }

        # 遠端裝置（upsmon.conf 非 localhost MONITOR 行）
        for my $m (_parse_monitor_lines()) {
            next if $m->{host} eq 'localhost';
            next if $local_names{$m->{name}};
            my $target = "$m->{name}\@$m->{host}:$m->{port}";
            push @result, {
                name     => $m->{name},
                type     => 'remote',
                host     => $m->{host},
                nutport  => $m->{port},
                username => $m->{username},
                status   => _check_device_status($target),
            };
        }

        return \@result;
    },
});

# ── POST /ups/config/devices ───────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'add_device',
    path        => 'devices',
    method      => 'POST',
    description => '新增或更新 UPS 裝置。type=usb|snmp 寫入 ups.conf；type=remote 寫入 upsmon.conf MONITOR 行。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            type => {
                type => 'string',
                enum => ['usb', 'snmp', 'remote'],
                description => '裝置類型',
            },
            name => {
                type    => 'string',
                pattern => '[a-zA-Z0-9_@.-]+',
                description => '裝置名稱',
            },
            oldname => {
                type     => 'string',
                optional => 1,
                pattern  => '[a-zA-Z0-9_@.-]+',
                description => '重新命名時的原始名稱',
            },
            # USB 欄位
            driver    => { type => 'string',  optional => 1, default => 'usbhid-ups' },
            port      => { type => 'string',  optional => 1, default => 'auto' },
            desc      => { type => 'string',  optional => 1, default => '' },
            serial    => { type => 'string',  optional => 1, pattern => '[a-zA-Z0-9_-]*' },
            vendorid  => { type => 'string',  optional => 1, pattern => '[0-9a-fA-F]{1,4}' },
            productid => { type => 'string',  optional => 1, pattern => '[0-9a-fA-F]{1,4}' },
            # SNMP 欄位
            snmphost     => { type => 'string',  optional => 1, description => 'SNMP 裝置 IP' },
            snmp_version => { type => 'string',  optional => 1, default => 'v2c',
                              enum => ['v1', 'v2c', 'v3'] },
            mibs         => { type => 'string',  optional => 1, default => 'ietf' },
            # SNMPv1/v2c 欄位
            community    => { type => 'string',  optional => 1, default => 'public' },
            # SNMPv3 欄位
            sec_level    => { type => 'string',  optional => 1,
                              enum => ['noAuthNoPriv', 'authNoPriv', 'authPriv'] },
            sec_name     => { type => 'string',  optional => 1 },
            auth_protocol => { type => 'string', optional => 1,
                               enum => ['MD5', 'SHA', 'SHA-256', 'SHA-384', 'SHA-512'] },
            auth_password => { type => 'string', optional => 1, minLength => 8 },
            priv_protocol => { type => 'string', optional => 1,
                               enum => ['DES', 'AES', 'AES-192', 'AES-256'] },
            priv_password => { type => 'string', optional => 1, minLength => 8 },
            # 遠端 NUT Server 欄位
            nuthost  => { type => 'string',  optional => 1 },
            nutport  => { type => 'integer', optional => 1, default => 3493,
                          minimum => 1, maximum => 65535 },
            username => { type => 'string',  optional => 1, default => 'upsmon' },
            password => { type => 'string',  optional => 1, default => '' },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        my $type    = $param->{type};
        my $name    = $param->{name} or die "Parameter 'name' required\n";
        my $oldname = $param->{oldname} // $name;

        _ensure_nut_dir();
        my $mode = _read_nut_mode();

        if ($type eq 'usb' || $type eq 'snmp') {
            # ── 更新 ups.conf ────────────────────────────────────────────
            my @devices = _parse_ups_conf();
            @devices = grep { $_->{name} ne $oldname && $_->{name} ne $name } @devices;

            my %dev = (name => $name);
            if ($type eq 'usb') {
                $dev{driver}    = $param->{driver}    // 'usbhid-ups';
                $dev{port}      = $param->{port}       // 'auto';
                $dev{desc}      = $param->{desc}       // '';
                $dev{serial}    = $param->{serial}     // '';
                $dev{vendorid}  = $param->{vendorid}   // '';
                $dev{productid} = $param->{productid}  // '';
            } else {
                my $snmphost = $param->{snmphost} or die "Parameter 'snmphost' required for snmp type\n";
                $snmphost =~ s/[^a-zA-Z0-9._:-]//g;
                $dev{driver}       = 'snmp-ups';
                $dev{port}         = $snmphost;
                $dev{snmp_version} = $param->{snmp_version} // 'v2c';
                $dev{mibs}         = $param->{mibs}         // 'ietf';
                $dev{desc}         = $param->{desc}         // '';
                if ($dev{snmp_version} eq 'v3') {
                    # SNMPv3：帳號 + 安全層級，不使用 community
                    $dev{seclevel} = $param->{sec_level} // 'noAuthNoPriv';
                    $dev{secname}  = $param->{sec_name}  // '';
                    my $lvl = $dev{seclevel};
                    if ($lvl eq 'authNoPriv' || $lvl eq 'authPriv') {
                        $dev{authprotocol} = $param->{auth_protocol} // 'SHA';
                        $dev{authpassword} = $param->{auth_password} // '';
                    }
                    if ($lvl eq 'authPriv') {
                        $dev{privprotocol} = $param->{priv_protocol} // 'AES';
                        $dev{privpassword} = $param->{priv_password} // '';
                    }
                } else {
                    # SNMPv1/v2c：使用 community string
                    $dev{community} = $param->{community} // 'public';
                }
            }
            push @devices, \%dev;

            # ── 準備本機帳號密碼，保留現有遠端帳號設定 ────────────────
            my $local_pass  = _get_or_create_local_password();
            my %usr         = _parse_upsd_users();
            my ($ruser, $rpass);
            for my $uname (sort keys %usr) {
                next if $uname eq 'upsmon_local' || $uname eq 'upsmon';
                next unless ($usr{$uname}{upsmon} // '') eq 'slave';
                $ruser = $uname;
                $rpass = $usr{$uname}{password};
                last;
            }

            # ── 更新 upsmon.conf：移除舊的 localhost monitor，加入新的 ─
            my @monitors = _parse_monitor_lines();
            @monitors = grep {
                !($_->{host} eq 'localhost' &&
                  ($_->{name} eq $oldname || $_->{name} eq $name))
            } @monitors;
            push @monitors, {
                name     => $name,
                host     => 'localhost',
                port     => 3493,
                username => 'upsmon_local',
                password => $local_pass,
                montype  => 'master',
            };
            # 遷移既有 localhost monitor 到新帳號（升級相容）
            for my $m (@monitors) {
                if ($m->{host} eq 'localhost') {
                    $m->{username} = 'upsmon_local';
                    $m->{password} = $local_pass;
                    $m->{montype}  = 'master';
                }
            }

            _write_file_safe($UPS_CONF,    _generate_ups_conf(@devices));
            _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@monitors));
            _write_file_safe($UPSD_USERS,  _generate_upsd_users($local_pass, $ruser, $rpass));
            _fix_nut_perms();
            _restart_services($mode);

        } elsif ($type eq 'remote') {
            my $host = $param->{nuthost} or die "Parameter 'nuthost' required for remote type\n";
            $host =~ s/[^a-zA-Z0-9._:-]//g;
            $name =~ s/[^a-zA-Z0-9_@.-]//g;

            my @monitors = _parse_monitor_lines();
            # 移除同名的舊遠端 monitor（rename 時同時移除舊名與新名）
            @monitors = grep {
                !($_->{host} ne 'localhost' &&
                  ($_->{name} eq $oldname || $_->{name} eq $name))
            } @monitors;
            push @monitors, {
                name     => $name,
                host     => $host,
                port     => $param->{nutport} // 3493,
                username => $param->{username} // 'upsmon',
                password => $param->{password} // '',
                montype  => 'slave',
            };

            _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@monitors));
            _fix_nut_perms();
            eval { run_command(['systemctl', 'restart', 'nut-monitor'], errmsg => 'restart nut-monitor') };
            warn "nut-monitor restart: $@" if $@;
        }

        return undef;
    },
});

# ── DELETE /ups/config/devices/{name} ─────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'delete_device',
    path        => 'devices/{name}',
    method      => 'DELETE',
    description => '刪除裝置：本機裝置從 ups.conf 移除，遠端裝置從 upsmon.conf MONITOR 移除。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            name => { type => 'string', pattern => '[a-zA-Z0-9_@.-]+' },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        my $name = $param->{name};

        # 嘗試從 ups.conf 移除
        my @local     = _parse_ups_conf();
        my @remaining = grep { $_->{name} ne $name } @local;
        _write_file_safe($UPS_CONF, _generate_ups_conf(@remaining))
            if scalar(@local) != scalar(@remaining);

        # 從 upsmon.conf 移除對應的 MONITOR 行，同步遷移本機帳號
        my @monitors  = _parse_monitor_lines();
        my @keep_mon  = grep { $_->{name} ne $name } @monitors;
        if (scalar(@monitors) != scalar(@keep_mon)) {
            my $local_pass = _get_or_create_local_password();
            for my $m (@keep_mon) {
                if ($m->{host} eq 'localhost') {
                    $m->{username} = 'upsmon_local';
                    $m->{password} = $local_pass;
                }
            }
            _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@keep_mon));
        }

        _fix_nut_perms();
        return undef;
    },
});

# ── GET /ups/config/server ────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'get_server',
    path        => 'server',
    method      => 'GET',
    description => '取得 NUT Server 設定：監聽位址、遠端帳號。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Audit']] },
    parameters  => {
        additionalProperties => 0,
        properties => { node => get_standard_option('pve-node') },
    },
    returns => {
        type => 'object',
        properties => {
            listen_addr         => { type => 'string' },
            remote_user         => { type => 'string' },
            has_remote_password => { type => 'integer' },
        },
        additionalProperties => 0,
    },
    code => sub {
        my %upsd = _read_upsd_conf();
        my %usr  = _parse_upsd_users();
        my ($ruser, $rhas_pass) = ('', 0);
        for my $uname (sort keys %usr) {
            next if $uname eq 'upsmon_local' || $uname eq 'upsmon';
            next unless ($usr{$uname}{upsmon} // '') eq 'slave';
            $ruser     = $uname;
            $rhas_pass = (defined $usr{$uname}{password} && $usr{$uname}{password} ne '') ? 1 : 0;
            last;
        }
        return {
            listen_addr         => $upsd{listen_addr},
            remote_user         => $ruser,
            has_remote_password => $rhas_pass,
        };
    },
});

# ── PUT /ups/config/server ────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'set_server',
    path        => 'server',
    method      => 'PUT',
    description => '設定 NUT Server 監聽位址與遠端 slave 帳號。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node            => get_standard_option('pve-node'),
            listen_addr     => { type => 'string', optional => 1, default => '0.0.0.0',
                                 pattern => '[a-zA-Z0-9.:*]+' },
            remote_user     => { type => 'string', optional => 1, default => '',
                                 pattern => '[a-zA-Z0-9_-]*' },
            remote_password => { type => 'string', optional => 1 },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        _ensure_nut_dir();

        my $listen_addr = $param->{listen_addr} // '0.0.0.0';
        my $remote_user = $param->{remote_user} // '';
        my $remote_pass = $param->{remote_password};

        # 若未提供新密碼，保留現有密碼
        if (!defined $remote_pass && $remote_user ne '') {
            my %usr = _parse_upsd_users();
            $remote_pass = $usr{$remote_user}{password} // '';
        }
        $remote_pass //= '';

        my $local_pass = _get_or_create_local_password();

        _write_file_safe($UPSD_CONF,  _generate_upsd_conf($listen_addr));
        _write_file_safe($UPSD_USERS, _generate_upsd_users($local_pass, $remote_user, $remote_pass));

        # 同步更新 upsmon.conf 中 localhost 監控帳號（遷移相容）
        my @monitors = _parse_monitor_lines();
        if (@monitors) {
            for my $m (@monitors) {
                if ($m->{host} eq 'localhost') {
                    $m->{username} = 'upsmon_local';
                    $m->{password} = $local_pass;
                }
            }
            _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@monitors));
        }

        _fix_nut_perms();
        _restart_services(_read_nut_mode());
        return undef;
    },
});

# ── POST /ups/config/service-restart ──────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'service_restart',
    path        => 'service-restart',
    method      => 'POST',
    description => '重啟指定的 NUT 服務。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node    => get_standard_option('pve-node'),
            service => {
                type => 'string',
                enum => ['nut-server', 'nut-monitor'],
            },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        run_command(['systemctl', 'restart', $param->{service}],
            errmsg => "Failed to restart $param->{service}");
        return undef;
    },
});

1;
