package PVE::API2::UPS::Config;

# PVE::API2::UPS::Config
# 掛載於 /nodes/{node}/ups/config
# 提供裝置 CRUD、全域模式設定、服務重啟端點。

use strict;
use warnings;

use PVE::RESTHandler;
use PVE::JSONSchema qw(get_standard_option);
use PVE::RPCEnvironment;
use PVE::Tools qw(run_command);

use base qw(PVE::RESTHandler);

my $NUT_CONF    = '/etc/nut/nut.conf';
my $UPS_CONF    = '/etc/nut/ups.conf';
my $UPSMON_CONF = '/etc/nut/upsmon.conf';
my $UPSD_USERS  = '/etc/nut/upsd.users';

# ── 輔助函式 ────────────────────────────────────────────────────────────────

sub _write_file_safe {
    my ($file, $content) = @_;
    my $tmp = "$file.tmp.$$";
    open(my $fh, '>', $tmp) or die "Cannot write $tmp: $!\n";
    print $fh $content;
    close $fh;
    rename($tmp, $file) or die "Cannot replace $file: $!\n";
}

sub _read_nut_mode {
    return 'standalone' unless -f $NUT_CONF;
    open(my $fh, '<', $NUT_CONF) or return 'standalone';
    while (<$fh>) {
        return $1 if /^\s*MODE\s*=\s*(\S+)/i;
    }
    close $fh;
    return 'standalone';
}

sub _generate_nut_conf {
    my ($mode) = @_;
    return "# Generated by pve-ups-panel\nMODE=$mode\n";
}

# 從 driver 名稱判斷裝置類型
sub _device_type {
    my ($driver) = @_;
    return 'snmp' if ($driver // '') eq 'snmp-ups';
    return 'usb';
}

# 解析 ups.conf → [{name, driver, port, ...}]
sub _parse_ups_conf {
    my @devices;
    return @devices unless -f $UPS_CONF;
    my $cur;
    open(my $fh, '<', $UPS_CONF) or return @devices;
    while (<$fh>) {
        chomp;
        s/\s*#.*$//;
        if (/^\[([^\]]+)\]/) {
            push @devices, $cur if $cur;
            $cur = { name => $1 };
        } elsif ($cur && /^\s*(\w+)\s*=\s*"?([^"]*)"?\s*$/) {
            $cur->{lc $1} = $2;
        }
    }
    push @devices, $cur if $cur;
    close $fh;
    return @devices;
}

sub _generate_ups_conf {
    my (@devices) = @_;
    my $out = "# Generated by pve-ups-panel\n\n";
    for my $d (@devices) {
        $out .= "[$d->{name}]\n";
        $out .= "    driver = $d->{driver}\n"              if $d->{driver};
        $out .= "    port = $d->{port}\n"                  if $d->{port};
        # USB 專用欄位
        $out .= "    serial = $d->{serial}\n"              if $d->{serial};
        $out .= "    vendorid = $d->{vendorid}\n"          if $d->{vendorid};
        $out .= "    productid = $d->{productid}\n"        if $d->{productid};
        # SNMP 專用欄位
        $out .= "    community = $d->{community}\n"        if $d->{community};
        $out .= "    snmp_version = $d->{snmp_version}\n"  if $d->{snmp_version};
        $out .= "    mibs = $d->{mibs}\n"                  if $d->{mibs};
        $out .= "    desc = \"$d->{desc}\"\n"              if $d->{desc};
        $out .= "\n";
    }
    return $out;
}

# 解析 upsmon.conf MONITOR 行 → [{name, host, port, username, password, montype}]
sub _parse_monitor_lines {
    my @monitors;
    return @monitors unless -f $UPSMON_CONF;
    open(my $fh, '<', $UPSMON_CONF) or return @monitors;
    while (<$fh>) {
        if (/^MONITOR\s+(\S+)\s+\d+\s+(\S+)\s+(\S+)\s+(\S+)/) {
            my ($target, $user, $pass, $montype) = ($1, $2, $3, $4);
            if ($target =~ /^([^@]+)\@([^:]+)(?::(\d+))?$/) {
                push @monitors, {
                    name     => $1,
                    host     => $2,
                    port     => defined $3 ? $3 + 0 : 3493,
                    username => $user,
                    password => $pass,
                    montype  => $montype,
                };
            }
        }
    }
    close $fh;
    return @monitors;
}

# 從 monitor 清單產生完整 upsmon.conf（自動保留既有 NOTIFYCMD/NOTIFYFLAG）
sub _build_upsmon_conf {
    my ($monitors) = @_;

    # 先讀出既有的通知設定行，再重寫檔案
    my @notify_lines;
    if (-f $UPSMON_CONF) {
        open(my $fh, '<', $UPSMON_CONF) or goto SKIP_NOTIFY;
        while (<$fh>) {
            push @notify_lines, $_ if /^NOTIFYCMD\s|^NOTIFYFLAG\s/;
        }
        close $fh;
    }
    SKIP_NOTIFY:

    my $out = "# Generated by pve-ups-panel\n\n";
    for my $m (@$monitors) {
        my $target = "$m->{name}\@$m->{host}";
        $target .= ":$m->{port}" if $m->{host} ne 'localhost' && $m->{port} != 3493;
        $out .= "MONITOR $target 1 $m->{username} $m->{password} $m->{montype}\n";
    }
    $out .= <<'END';

SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
POWERDOWNFLAG /etc/killpower
RBWARNTIME 43200
NOCOMMWARNTIME 300
FINALDELAY 5
END
    $out .= "\n" . join('', @notify_lines) if @notify_lines;
    return $out;
}

sub _generate_upsd_users {
    return <<'END';
# Generated by pve-ups-panel
[upsmon]
    password = localmonitor
    upsmon master
END
}

sub _check_device_status {
    my ($target) = @_;
    my $connected = 0;
    eval {
        open(my $fh, '-|', '/bin/upsc', $target) or die;
        while (<$fh>) { if (/^ups\.status:/) { $connected = 1; last; } }
        close $fh;
    };
    return $connected ? 'connected' : 'disconnected';
}

sub _ensure_nut_dir {
    unless (-d '/etc/nut') {
        mkdir '/etc/nut', 0750 or die "Cannot create /etc/nut: $!\n";
    }
}

sub _fix_nut_perms {
    run_command(['chown', '-R', 'root:nut', '/etc/nut'],
        errmsg => 'chown /etc/nut failed', noerr => 1);
    for my $f ($NUT_CONF, $UPS_CONF, $UPSMON_CONF, $UPSD_USERS) {
        chmod 0640, $f if -f $f;
    }
}

sub _restart_services {
    my ($mode) = @_;
    if (($mode // '') eq 'standalone' || ($mode // '') eq 'netserver') {
        eval { run_command(['systemctl', 'restart', 'nut-server'], errmsg => 'restart nut-server') };
        warn "nut-server restart: $@" if $@;
        sleep 1;
    }
    eval { run_command(['systemctl', 'restart', 'nut-monitor'], errmsg => 'restart nut-monitor') };
    warn "nut-monitor restart: $@" if $@;
}

# ── GET /ups/config/mode ───────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'get_mode',
    path        => 'mode',
    method      => 'GET',
    description => '取得目前 NUT 全域模式（standalone / netserver）。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Audit']] },
    parameters  => {
        additionalProperties => 0,
        properties => { node => get_standard_option('pve-node') },
    },
    returns => {
        type => 'object',
        properties => { mode => { type => 'string' } },
        additionalProperties => 0,
    },
    code => sub { return { mode => _read_nut_mode() }; },
});

# ── PUT /ups/config/mode ───────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'set_mode',
    path        => 'mode',
    method      => 'PUT',
    description => '設定 NUT 全域模式（standalone / netserver）並重啟相關服務。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            mode => { type => 'string', enum => ['standalone', 'netserver'] },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        _ensure_nut_dir();
        _write_file_safe($NUT_CONF, _generate_nut_conf($param->{mode}));
        _fix_nut_perms();
        _restart_services($param->{mode});
        return undef;
    },
});

# ── GET /ups/config/devices ────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'list_devices',
    path        => 'devices',
    method      => 'GET',
    description => '列出所有 UPS 裝置（本機 USB/SNMP + 遠端 NUT Server MONITOR）。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Audit']] },
    parameters  => {
        additionalProperties => 0,
        properties => { node => get_standard_option('pve-node') },
    },
    returns => {
        type  => 'array',
        items => {
            type => 'object',
            properties => {
                name    => { type => 'string' },
                type    => { type => 'string', description => 'usb | snmp | remote' },
                status  => { type => 'string', description => 'connected | disconnected' },
                driver  => { type => 'string', optional => 1 },
                port    => { type => 'string', optional => 1 },
                host    => { type => 'string', optional => 1 },
                nutport => { type => 'integer', optional => 1 },
            },
            additionalProperties => 1,
        },
    },
    code => sub {
        my @result;
        my %local_names;

        # 本機裝置（ups.conf）
        for my $d (_parse_ups_conf()) {
            my $type = _device_type($d->{driver});
            $local_names{$d->{name}} = 1;
            push @result, {
                %$d,
                type   => $type,
                status => _check_device_status("$d->{name}\@localhost"),
            };
        }

        # 遠端裝置（upsmon.conf 非 localhost MONITOR 行）
        for my $m (_parse_monitor_lines()) {
            next if $m->{host} eq 'localhost';
            next if $local_names{$m->{name}};
            my $target = "$m->{name}\@$m->{host}:$m->{port}";
            push @result, {
                name     => $m->{name},
                type     => 'remote',
                host     => $m->{host},
                nutport  => $m->{port},
                username => $m->{username},
                status   => _check_device_status($target),
            };
        }

        return \@result;
    },
});

# ── POST /ups/config/devices ───────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'add_device',
    path        => 'devices',
    method      => 'POST',
    description => '新增或更新 UPS 裝置。type=usb|snmp 寫入 ups.conf；type=remote 寫入 upsmon.conf MONITOR 行。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            type => {
                type => 'string',
                enum => ['usb', 'snmp', 'remote'],
                description => '裝置類型',
            },
            name => {
                type    => 'string',
                pattern => '[a-zA-Z0-9_@.-]+',
                description => '裝置名稱',
            },
            oldname => {
                type     => 'string',
                optional => 1,
                pattern  => '[a-zA-Z0-9_@.-]+',
                description => '重新命名時的原始名稱',
            },
            # USB 欄位
            driver    => { type => 'string',  optional => 1, default => 'usbhid-ups' },
            port      => { type => 'string',  optional => 1, default => 'auto' },
            desc      => { type => 'string',  optional => 1, default => '' },
            serial    => { type => 'string',  optional => 1, pattern => '[a-zA-Z0-9_-]*' },
            vendorid  => { type => 'string',  optional => 1, pattern => '[0-9a-fA-F]{1,4}' },
            productid => { type => 'string',  optional => 1, pattern => '[0-9a-fA-F]{1,4}' },
            # SNMP 欄位
            snmphost     => { type => 'string',  optional => 1, description => 'SNMP 裝置 IP' },
            community    => { type => 'string',  optional => 1, default => 'public' },
            snmp_version => { type => 'string',  optional => 1, default => 'v2c',
                              enum => ['v1', 'v2c', 'v3'] },
            mibs         => { type => 'string',  optional => 1, default => 'ietf' },
            # 遠端 NUT Server 欄位
            nuthost  => { type => 'string',  optional => 1 },
            nutport  => { type => 'integer', optional => 1, default => 3493,
                          minimum => 1, maximum => 65535 },
            username => { type => 'string',  optional => 1, default => 'upsmon' },
            password => { type => 'string',  optional => 1, default => '' },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        my $type    = $param->{type};
        my $name    = $param->{name} or die "Parameter 'name' required\n";
        my $oldname = $param->{oldname} // $name;

        _ensure_nut_dir();
        my $mode = _read_nut_mode();

        if ($type eq 'usb' || $type eq 'snmp') {
            # ── 更新 ups.conf ────────────────────────────────────────────
            my @devices = _parse_ups_conf();
            @devices = grep { $_->{name} ne $oldname && $_->{name} ne $name } @devices;

            my %dev = (name => $name);
            if ($type eq 'usb') {
                $dev{driver}    = $param->{driver}    // 'usbhid-ups';
                $dev{port}      = $param->{port}       // 'auto';
                $dev{desc}      = $param->{desc}       // '';
                $dev{serial}    = $param->{serial}     // '';
                $dev{vendorid}  = $param->{vendorid}   // '';
                $dev{productid} = $param->{productid}  // '';
            } else {
                my $snmphost = $param->{snmphost} or die "Parameter 'snmphost' required for snmp type\n";
                $snmphost =~ s/[^a-zA-Z0-9._:-]//g;
                $dev{driver}       = 'snmp-ups';
                $dev{port}         = $snmphost;
                $dev{community}    = $param->{community}    // 'public';
                $dev{snmp_version} = $param->{snmp_version} // 'v2c';
                $dev{mibs}         = $param->{mibs}         // 'ietf';
                $dev{desc}         = $param->{desc}         // '';
            }
            push @devices, \%dev;

            # ── 更新 upsmon.conf：移除舊的 localhost monitor，加入新的 ─
            my @monitors = _parse_monitor_lines();
            @monitors = grep {
                !($_->{host} eq 'localhost' &&
                  ($_->{name} eq $oldname || $_->{name} eq $name))
            } @monitors;
            push @monitors, {
                name     => $name,
                host     => 'localhost',
                port     => 3493,
                username => 'upsmon',
                password => 'localmonitor',
                montype  => 'master',
            };

            _write_file_safe($UPS_CONF,    _generate_ups_conf(@devices));
            _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@monitors));
            _write_file_safe($UPSD_USERS,  _generate_upsd_users());
            _fix_nut_perms();
            _restart_services($mode);

        } elsif ($type eq 'remote') {
            my $host = $param->{nuthost} or die "Parameter 'nuthost' required for remote type\n";
            $host =~ s/[^a-zA-Z0-9._:-]//g;
            $name =~ s/[^a-zA-Z0-9_@.-]//g;

            my @monitors = _parse_monitor_lines();
            # 移除同名的舊遠端 monitor（rename 時同時移除舊名與新名）
            @monitors = grep {
                !($_->{host} ne 'localhost' &&
                  ($_->{name} eq $oldname || $_->{name} eq $name))
            } @monitors;
            push @monitors, {
                name     => $name,
                host     => $host,
                port     => $param->{nutport} // 3493,
                username => $param->{username} // 'upsmon',
                password => $param->{password} // '',
                montype  => 'slave',
            };

            _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@monitors));
            _fix_nut_perms();
            eval { run_command(['systemctl', 'restart', 'nut-monitor'], errmsg => 'restart nut-monitor') };
            warn "nut-monitor restart: $@" if $@;
        }

        return undef;
    },
});

# ── DELETE /ups/config/devices/{name} ─────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'delete_device',
    path        => 'devices/{name}',
    method      => 'DELETE',
    description => '刪除裝置：本機裝置從 ups.conf 移除，遠端裝置從 upsmon.conf MONITOR 移除。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            name => { type => 'string', pattern => '[a-zA-Z0-9_@.-]+' },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        my $name = $param->{name};

        # 嘗試從 ups.conf 移除
        my @local     = _parse_ups_conf();
        my @remaining = grep { $_->{name} ne $name } @local;
        _write_file_safe($UPS_CONF, _generate_ups_conf(@remaining))
            if scalar(@local) != scalar(@remaining);

        # 從 upsmon.conf 移除對應的 MONITOR 行
        my @monitors  = _parse_monitor_lines();
        my @keep_mon  = grep { $_->{name} ne $name } @monitors;
        _write_file_safe($UPSMON_CONF, _build_upsmon_conf(\@keep_mon))
            if scalar(@monitors) != scalar(@keep_mon);

        _fix_nut_perms();
        return undef;
    },
});

# ── POST /ups/config/service-restart ──────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'service_restart',
    path        => 'service-restart',
    method      => 'POST',
    description => '重啟指定的 NUT 服務。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node    => get_standard_option('pve-node'),
            service => {
                type => 'string',
                enum => ['nut-server', 'nut-monitor'],
            },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        run_command(['systemctl', 'restart', $param->{service}],
            errmsg => "Failed to restart $param->{service}");
        return undef;
    },
});

1;
