package PVE::API2::UPS::Config;

# PVE::API2::UPS::Config
# 掛載於 /nodes/{node}/ups/config
# 提供裝置 CRUD、設定讀寫、服務重啟端點。

use strict;
use warnings;

use PVE::RESTHandler;
use PVE::JSONSchema qw(get_standard_option);
use PVE::RPCEnvironment;
use PVE::Tools qw(run_command);

use base qw(PVE::RESTHandler);

my $NUT_CONF    = '/etc/nut/nut.conf';
my $UPS_CONF    = '/etc/nut/ups.conf';
my $UPSMON_CONF = '/etc/nut/upsmon.conf';
my $UPSD_USERS  = '/etc/nut/upsd.users';

# ── 輔助函式 ────────────────────────────────────────────────────────────────

sub _write_file_safe {
    my ($file, $content) = @_;
    my $tmp = "$file.tmp.$$";
    open(my $fh, '>', $tmp) or die "Cannot write $tmp: $!\n";
    print $fh $content;
    close $fh;
    rename($tmp, $file) or die "Cannot replace $file: $!\n";
}

# 解析 ups.conf 回傳 [{name, driver, port, desc}, ...]
sub _parse_ups_conf {
    my @devices;
    return @devices unless -f $UPS_CONF;
    my $cur;
    open(my $fh, '<', $UPS_CONF) or return @devices;
    while (<$fh>) {
        chomp;
        s/\s*#.*$//;          # 去除行末註解
        if (/^\[([^\]]+)\]/) {
            push @devices, $cur if $cur;
            $cur = { name => $1 };
        } elsif ($cur && /^\s*(\w+)\s*=\s*"?([^"]*)"?\s*$/) {
            $cur->{lc $1} = $2;
        }
    }
    push @devices, $cur if $cur;
    close $fh;
    return @devices;
}

sub _generate_nut_conf {
    my ($mode) = @_;
    return "# Generated by pve-ups-panel\nMODE=$mode\n";
}

sub _generate_ups_conf {
    my (@devices) = @_;
    my $out = "# Generated by pve-ups-panel\n\n";
    for my $d (@devices) {
        $out .= "[$d->{name}]\n";
        $out .= "    driver = $d->{driver}\n"         if $d->{driver};
        $out .= "    port = $d->{port}\n"             if $d->{port};
        $out .= "    serial = $d->{serial}\n"         if $d->{serial};
        $out .= "    vendorid = $d->{vendorid}\n"     if $d->{vendorid};
        $out .= "    productid = $d->{productid}\n"   if $d->{productid};
        $out .= "    desc = \"$d->{desc}\"\n"         if $d->{desc};
        $out .= "\n";
    }
    return $out;
}

sub _generate_upsmon_conf_standalone {
    my (@devices) = @_;
    my $out = "# Generated by pve-ups-panel\n\n";
    for my $d (@devices) {
        $out .= "MONITOR $d->{name}\@localhost 1 upsmon localmonitor master\n";
    }
    $out .= <<'END';

SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
POWERDOWNFLAG /etc/killpower
RBWARNTIME 43200
NOCOMMWARNTIME 300
FINALDELAY 5
END
    return $out;
}

sub _generate_upsmon_conf_netclient {
    my ($ups, $host, $port, $user, $pass) = @_;
    my $out = "# Generated by pve-ups-panel\n\n";
    $out .= "MONITOR $ups\@$host:$port 1 $user $pass slave\n\n";
    $out .= <<'END';
SHUTDOWNCMD "/sbin/shutdown -h +0"
POLLFREQ 5
POLLFREQALERT 5
HOSTSYNC 15
DEADTIME 15
POWERDOWNFLAG /etc/killpower
RBWARNTIME 43200
NOCOMMWARNTIME 300
FINALDELAY 5
END
    return $out;
}

sub _generate_upsd_users {
    return <<'END';
# Generated by pve-ups-panel
[upsmon]
    password = localmonitor
    upsmon master
END
}

sub _read_nut_mode {
    return 'standalone' unless -f $NUT_CONF;
    open(my $fh, '<', $NUT_CONF) or return 'standalone';
    while (<$fh>) {
        return $1 if /^\s*MODE\s*=\s*(\S+)/i;
    }
    close $fh;
    return 'standalone';
}

sub _check_device_status {
    my ($name) = @_;
    my $connected = 0;
    eval {
        open(my $fh, '-|', '/bin/upsc', $name) or die;
        while (<$fh>) { if (/^ups\.status:/) { $connected = 1; last; } }
        close $fh;
    };
    return $connected ? 'connected' : 'disconnected';
}

# 從現有 upsmon.conf 讀出通知相關行（NOTIFYCMD / NOTIFYFLAG），
# 在重寫設定檔後補回，避免 Wizard 覆蓋 Notify.pm 寫入的設定。
sub _extract_notify_lines {
    my @lines;
    return @lines unless -f $UPSMON_CONF;
    open(my $fh, '<', $UPSMON_CONF) or return @lines;
    while (<$fh>) {
        push @lines, $_ if /^NOTIFYCMD\s|^NOTIFYFLAG\s/;
    }
    close $fh;
    return @lines;
}

sub _ensure_nut_dir {
    unless (-d '/etc/nut') {
        mkdir '/etc/nut', 0750 or die "Cannot create /etc/nut: $!\n";
    }
}

sub _fix_nut_perms {
    run_command(['chown', '-R', 'root:nut', '/etc/nut'],
        errmsg => 'chown /etc/nut failed', noerr => 1);
    for my $f ($NUT_CONF, $UPS_CONF, $UPSMON_CONF, $UPSD_USERS) {
        chmod 0640, $f if -f $f;
    }
}

# ── GET /ups/config/devices ────────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'list_devices',
    path        => 'devices',
    method      => 'GET',
    description => '列出 ups.conf 中已設定的裝置，並附上連線狀態與 NUT 模式。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Audit']] },
    parameters  => {
        additionalProperties => 0,
        properties => { node => get_standard_option('pve-node') },
    },
    returns => {
        type  => 'array',
        items => {
            type => 'object',
            properties => {
                name   => { type => 'string' },
                driver => { type => 'string', optional => 1 },
                port   => { type => 'string', optional => 1 },
                desc   => { type => 'string', optional => 1 },
                serial => { type => 'string', optional => 1 },
                status => { type => 'string', description => 'connected | disconnected' },
                mode   => { type => 'string', description => 'NUT mode from nut.conf' },
            },
            additionalProperties => 1,
        },
    },
    code => sub {
        my $mode = _read_nut_mode();
        my @devices = _parse_ups_conf();
        for my $d (@devices) {
            $d->{status} = _check_device_status($d->{name} . '@localhost');
            $d->{mode}   = $mode;
        }
        return \@devices;
    },
});

# ── POST /ups/config/devices ───────────────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'add_device',
    path        => 'devices',
    method      => 'POST',
    description => '新增 UPS 裝置並套用 NUT 設定（寫入設定檔 + 重啟服務）。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node     => get_standard_option('pve-node'),
            mode     => {
                type        => 'string',
                enum        => ['standalone', 'netserver', 'netclient'],
                default     => 'standalone',
                optional    => 1,
                description => 'NUT 運作模式',
            },
            # standalone / netserver
            name     => {
                type        => 'string',
                pattern     => '[a-zA-Z0-9_@.-]+',
                optional    => 1,
                description => '裝置名稱（ups.conf section）',
            },
            driver   => {
                type     => 'string',
                optional => 1,
                default  => 'usbhid-ups',
            },
            port     => {
                type     => 'string',
                optional => 1,
                default  => 'auto',
            },
            desc     => { type => 'string', optional => 1, default => '' },
            serial    => { type => 'string', optional => 1,
                           pattern => '[a-zA-Z0-9_-]*',
                           description => 'Bind driver to this UPS serial number' },
            vendorid  => { type => 'string', optional => 1,
                           pattern => '[0-9a-fA-F]{1,4}',
                           description => 'USB Vendor ID (4 hex digits)' },
            productid => { type => 'string', optional => 1,
                           pattern => '[0-9a-fA-F]{1,4}',
                           description => 'USB Product ID (4 hex digits)' },
            oldname   => { type => 'string', optional => 1,
                           pattern => '[a-zA-Z0-9_@.-]+',
                           description => '編輯時的原始裝置名稱，用於重新命名' },
            # netclient
            nuthost  => { type => 'string',  optional => 1, description => '遠端 NUT Server 位址' },
            nutport  => { type => 'integer', optional => 1, default => 3493, minimum => 1, maximum => 65535 },
            username => { type => 'string',  optional => 1 },
            password => { type => 'string',  optional => 1 },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;

        my $mode = $param->{mode} // 'standalone';
        _ensure_nut_dir();

        if ($mode eq 'standalone' || $mode eq 'netserver') {
            my $name      = $param->{name}   or die "Parameter 'name' required for $mode mode\n";
            my $driver    = $param->{driver}    // 'usbhid-ups';
            my $port      = $param->{port}      // 'auto';
            my $desc      = $param->{desc}      // '';
            my $serial    = $param->{serial}    // '';
            my $vendorid  = $param->{vendorid}  // '';
            my $productid = $param->{productid} // '';

            # 讀取現有裝置，移除目標條目後加入新條目
            # oldname 有值表示改名：同時移除舊名稱與新名稱的條目
            my $oldname = $param->{oldname} // $name;
            my @devices = _parse_ups_conf();
            @devices = grep { $_->{name} ne $oldname && $_->{name} ne $name } @devices;
            push @devices, { name => $name, driver => $driver, port => $port,
                             desc => $desc, serial => $serial,
                             vendorid => $vendorid, productid => $productid };

            my @notify_lines = _extract_notify_lines();
            my $upsmon = _generate_upsmon_conf_standalone(@devices);
            $upsmon .= "\n" . join('', @notify_lines) if @notify_lines;

            _write_file_safe($NUT_CONF,    _generate_nut_conf($mode));
            _write_file_safe($UPS_CONF,    _generate_ups_conf(@devices));
            _write_file_safe($UPSMON_CONF, $upsmon);
            _write_file_safe($UPSD_USERS,  _generate_upsd_users());
            _fix_nut_perms();

            eval {
                run_command(['systemctl', 'restart', 'nut-server'],
                    errmsg => 'restart nut-server');
            };
            warn "nut-server restart: $@" if $@;
            sleep 1;
            eval {
                run_command(['systemctl', 'restart', 'nut-client'],
                    errmsg => 'restart nut-client');
            };
            warn "nut-client restart: $@" if $@;

        } elsif ($mode eq 'netclient') {
            my $host = $param->{nuthost}  or die "Parameter 'nuthost' required for netclient mode\n";
            my $port = $param->{nutport}  // 3493;
            my $ups  = $param->{name}     // 'ups';
            my $user = $param->{username} // 'upsmon';
            my $pass = $param->{password} // '';

            $host =~ s/[^a-zA-Z0-9._-]//g;
            $ups  =~ s/[^a-zA-Z0-9_@.-]//g;

            my @notify_lines = _extract_notify_lines();
            my $upsmon = _generate_upsmon_conf_netclient($ups, $host, $port, $user, $pass);
            $upsmon .= "\n" . join('', @notify_lines) if @notify_lines;

            _write_file_safe($NUT_CONF,    _generate_nut_conf('netclient'));
            _write_file_safe($UPS_CONF,    "# Generated by pve-ups-panel\n# netclient mode — no local devices\n");
            _write_file_safe($UPSMON_CONF, $upsmon);
            _fix_nut_perms();

            eval {
                run_command(['systemctl', 'restart', 'nut-client'],
                    errmsg => 'restart nut-client');
            };
            warn "nut-client restart: $@" if $@;
        }

        return undef;
    },
});

# ── DELETE /ups/config/devices/{name} ─────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'delete_device',
    path        => 'devices/{name}',
    method      => 'DELETE',
    description => '從 ups.conf 移除指定裝置。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node => get_standard_option('pve-node'),
            name => { type => 'string', pattern => '[a-zA-Z0-9_@.-]+' },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        my @devices = _parse_ups_conf();
        @devices = grep { $_->{name} ne $param->{name} } @devices;
        _write_file_safe($UPS_CONF, _generate_ups_conf(@devices));
        return undef;
    },
});

# ── POST /ups/config/service-restart ─────────────────────────────────────
__PACKAGE__->register_method({
    name        => 'service_restart',
    path        => 'service-restart',
    method      => 'POST',
    description => '重啟指定的 NUT 服務。',
    protected   => 1,
    proxyto     => 'node',
    permissions => { check => ['perm', '/nodes/{node}', ['Sys.Modify']] },
    parameters  => {
        additionalProperties => 0,
        properties => {
            node    => get_standard_option('pve-node'),
            service => {
                type => 'string',
                enum => ['nut-server', 'nut-client'],
            },
        },
    },
    returns => { type => 'null' },
    code => sub {
        my ($param) = @_;
        run_command(['systemctl', 'restart', $param->{service}],
            errmsg => "Failed to restart $param->{service}");
        return undef;
    },
});

1;
